DBAAS-287 Instance provisioning error with Atlas Project credentials …
RHEcosystemAppEng/mongodb-atlas-kubernetes pull request #28
Opened 2022-02-04 14:01 UTC by jianrongzhang89

This PR fixes the issues on handling Atlas Project during provisioning. An Atlas Project is required to provision a new Atlas Cluster, and the same project can have multiple clusters, however for each project, at most one free trial instance (M0) is allowed. In addition, since the AtlasProject CR uses the same credentials as MongoDBAtlasInventory, the AtlasProject CR must be located in the same namespace as the inventory CR, because currently, MongoDB Atlas Operator core does not support credentials cross namepsaces. In addition when a cluster is being provisioned, there is some period when the cluster has not been created in Atlas, and the MongDBInstance should indicate that provisioning is pending.

2022-02-07 22:07 UTC, tchughesiv requested changes
can we add some unit tests?

2022-02-07 22:13 UTC, tchughesiv commented
> can we add some unit tests?

seems we already have tests, just make sure we have coverage

2022-02-08 19:20 UTC, jianrongzhang89 commented
> can we add some unit tests?

I added the unit test for the instance controller.

2022-02-08 19:37 UTC, tchughesiv approved these changes
lgtm

2022-02-08 19:39 UTC, merged