Change user agent to identify RHODA usage
RHEcosystemAppEng/mongodb-atlas-kubernetes pull request #46
Opened 2022-04-28 15:09 UTC by priyolahiri

This modifies the user agent string to include "RHODA" so that we can better understand RHODA usage through our analytics layer.

2022-05-04 13:26 UTC, jeremyary commented
Hey @tchughesiv @myeung18 this small update would allow Mongo to track usage of our version separately. PTAL? Thanks!

2022-05-04 13:43 UTC, jianrongzhang89 requested changes
Since our RHODA changes for mongodb atlas operator have not been merged by upstream (https://github.com/mongodb/mongodb-atlas-kubernetes/pull/312), this change should be targeted to the dbaas-refactor-rebased branch on RHEcosystemAppEng fork instead of main.

2022-05-04 13:52 UTC, myeung18 commented
> Hey @tchughesiv @myeung18 this small update would allow Mongo to track usage of our version separately. PTAL? Thanks!

FYI
A RP in ccapi is adding the userAgent header as well.
`UserAgent = "ccapi-k8s-operator"`

2022-05-23 13:42 UTC, jianrongzhang89 commented
Hi @igor-karpukhin @priyolahiri can you resubmit this PR against RHEcosystemAppEng/dbaas-refactor-rebased branch? This is where the RHODA release build is based on. Thanks.

2022-05-23 13:46 UTC, tchughesiv commented
@igor-karpukhin @priyolahiri @jianrongzhang89 i was able to change PR base branch

2022-05-23 13:51 UTC, jianrongzhang89 commented
Thanks @tchughesiv .

2022-05-23 13:52 UTC, jianrongzhang89 commented
LGTM

2022-05-23 13:52 UTC, merged

2022-05-23 13:58 UTC, jianrongzhang89 commented
Thank you Tommy. Can you update the other PR too?
https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/pull/47

*Jianrong Zhang*

Principal  Software Engineer

Ecosystem Engineering - Application Engineering

Red Hat <https://www.redhat.com/>

***@***.***

M: 1-9783923964
<https://red.ht/sig>


On Mon, May 23, 2022 at 9:46 AM Tommy Hughes IV ***@***.***>
wrote:

> @igor-karpukhin <https://github.com/igor-karpukhin> @priyolahiri
> <https://github.com/priyolahiri> @jianrongzhang89
> <https://github.com/jianrongzhang89> i was able to change PR base branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/pull/46#issuecomment-1134700635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMMXXMARTMUYWUIARCJE5DVLOD2TANCNFSM5USXOTKQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>