DBAAS-906 [RHODA][R4] Operator Metrics - Instance with Pending status on Thanos loaded on Grafana with status True
RHEcosystemAppEng/mongodb-atlas-kubernetes pull request #62
Opened 2022-09-28 00:38 UTC by jianrongzhang89

2022-10-12 16:03 UTC, jianrongzhang89 commented
PR for Mongo Atlas Operator for review: https://github.com/RHEcosystemAppEng/mongodb-atlas-kubernetes/pull/62

2022-10-21 14:19 UTC, tchughesiv requested changes
seeing this failure when running unit test -
```shell
% make unit-test
go test -race -cover ./pkg/...
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/dbaas	[no test files]
ok  	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1	(cached)	coverage: 3.1% of statements
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1/authmode	[no test files]
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1/common	[no test files]
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1/project	[no test files]
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1/provider	[no test files]
?   	github.com/mongodb/mongodb-atlas-kubernetes/pkg/api/v1/status	[no test files]
ok  	github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlas	(cached)	coverage: 56.4% of statements
ok  	github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasconnection	0.836s	coverage: 66.5% of statements
ok  	github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdatabaseuser	(cached)	coverage: 11.5% of statements
ok  	github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment	(cached)	coverage: 8.2% of statements
--- FAIL: TestSetInstanceStatusWithDeploymentInfo (0.01s)
    --- FAIL: TestSetInstanceStatusWithDeploymentInfo/DeploymentCreating (0.00s)
        atlasinstance_test.go:340: 
            	Error Trace:	atlasinstance_test.go:340
            	Error:      	Not equal: 
            	            	expected: "False"
            	            	actual  : "True"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-False
            	            	+True
            	Test:       	TestSetInstanceStatusWithDeploymentInfo/DeploymentCreating
FAIL
```

2022-10-21 20:25 UTC, jianrongzhang89 commented
@tchughesiv Fixed the unit test case.

2022-10-24 14:03 UTC, redhatHameed reviewed
@jianrongzhang89 added few minor comments

2022-10-24 14:03 UTC, redhatHameed commented on config/manager/manager.yaml
> +              value: "180"
do required this change ?

2022-10-24 14:03 UTC, redhatHameed commented on pkg/controller/atlasinstance/atlasinstance_controller.go
> +				} else {
can we add return here,  and remove else WDYT ?

2022-10-24 14:46 UTC, jianrongzhang89 commented on config/manager/manager.yaml
> +              value: "180"
Yes. It fixes the issue found by the linter.

2022-10-24 14:51 UTC, jianrongzhang89 commented on pkg/controller/atlasinstance/atlasinstance_controller.go
> +				} else {
Good idea. Done.

2022-10-24 14:56 UTC, redhatHameed approved these changes

2022-10-24 18:12 UTC, merged