DBAAS-956 MongoDB Atlas Operator incorrectly sets host to empty when processing connections
RHEcosystemAppEng/mongodb-atlas-kubernetes pull request #63
Opened 2022-10-19 13:45 UTC by jianrongzhang89

When a DBaaSConnection is created with a reference of DBaaSInstancen for mongodb using the Red Hat GitOps operator, the connection CR may have its configmap created with an empty host string set. As a result, the application would fail to run as the host string from the service binding is empty.

The solution is to check if the connection string is empty before creating the configmap/secret for connections.

Fix tested on the devt cluster successfully.

2022-10-19 14:08 UTC, tchughesiv reviewed
@jianrongzhang89 did you intend to target the `main` branch with this PR?

2022-10-19 14:22 UTC, jianrongzhang89 commented
@tchughesiv it should be dbaas-refactor-rebased branch. I updated the PR.

2022-10-19 14:44 UTC, tchughesiv requested changes
looks good but can we add a unit test for this change?

2022-10-19 18:04 UTC, jianrongzhang89 commented
@tchughesiv Thanks. Unit test case added.

2022-10-21 13:29 UTC, tchughesiv approved these changes
lgtm

2022-10-21 13:43 UTC, merged